theme = "anatole"
enableEmoji = true
baseURL = "https://raze.mx/"
enableRobotsTXT = true

# Enable Disqus
disqusShortname = "razes-blog"

# Google Analytics
# googleAnalytics = "UA-160623950-1"

# Syntax highlighting
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[params]
title = "Jorge Raze"
author = "Jorge Raze"
description = "Software Consultant, Cloud Architect and DevOps Practitioner"
profilePicture = "images/profile.png"
#copyright = "2021"
keywords = "tech, cloud, data"
favicon = "favicons/"
# example ["css/custom.css"]
customCss = []
# example ["js/custom.js"]
customJs = [] 
mainSections = ["post"]
images = ["images/site-feature-image.png"]
doNotLoadAnimations = false
# Form Spree Contact Form
contactFormAction = "https://formspree.io/f/mwkwzokv"
# Google Site Verify
googleSiteVerify = "EeaO-Mo1Xr4Ps8bEAit7Skg30LW1x4UEUUZy7U7KdvY"
# indexDateFormat = "Mon, Jan 2, 2006"
# listDateFormat = "Jan 2"
# singleDateFormat = "Mon, Jan 2, 2006"
displayMode = "dark"

[params.simpleAnalytics]
# enable = true
# customurl = "https://analytics.example.com"

## Math settings
[params.math]
enable = true  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/razeonex/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/razeone"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:hello@raze.mx"

[[params.socialIcons]]
icon = "fab fa-flickr"
title = "Flickr"
url = "https://www.flickr.com/photos/razeone/"

## Menu items

[menu]

  [[menu.main]]
  name = "Home"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Posts"
  weight = 200
  identifier = "posts"
  url = "/post/"

  [[menu.main]]
  name = "About"
  weight = 300
  identifier = "about"
  url = "/about/"

  [[menu.main]]
  name = "Contact"
  weight = 400
  identifier = "contact"
  url = "/contact/"
