name: Deploy Hugo Blog to AWS (OIDC)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  HUGO_VERSION: '0.150.0'
  S3_BUCKET: 'raze-website'
  CLOUDFRONT_DISTRIBUTION_ID: 'ES52SN9381PAQ'
  AWS_REGION: 'us-east-1'

permissions:
  id-token: write   # Required for OIDC
  contents: read    # Required for checkout

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: ${{ env.HUGO_VERSION }}
        extended: true

    - name: Build Hugo site
      run: |
        echo "Building Hugo site..."
        hugo --minify

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: hugo-site
        path: public/
        retention-days: 1

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: hugo-site
        path: public/

    - name: Configure AWS credentials (OIDC)
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
        role-session-name: GitHubActionsDeployment
        aws-region: ${{ env.AWS_REGION }}

    - name: Deploy to S3 and invalidate CloudFront
      run: |
        echo "Deploying to S3..."
        aws s3 sync ./public/ s3://${{ env.S3_BUCKET }} --delete
        
        echo "Creating CloudFront invalidation..."
        aws cloudfront create-invalidation \
          --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} \
          --paths "/*"
        
        echo "🎉 Deployment completed!"